<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv [
  <!ELEMENT cv (personalInformation, education, projects, skills)>
  <!ELEMENT personalInformation (firstName, lastName, address, email, phone)>
  <!ELEMENT firstName (#PCDATA)>
  <!ELEMENT lastName (#PCDATA)>
  <!ELEMENT address (Country, city, zipCode)>
  <!ELEMENT Country (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT zipCode (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  
  <!ELEMENT education (degree+)>
  <!ELEMENT degree (title, school, year)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT school (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  
  <!ELEMENT projects (project+)>
  <!ELEMENT project (title, description ?, year)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT skills (programmingLanguages, frameworks, Design, languages)>
  <!ELEMENT programmingLanguages (language+)>
  <!ELEMENT language (#PCDATA)>
  <!ELEMENT frameworks (framework+)>
  <!ELEMENT framework (#PCDATA)>
  <!ELEMENT Design (logiciel+)>
  <!ELEMENT logiciel (#PCDATA)>
  <!ELEMENT languages (language+)>
]>


<cv>
  <personalInformation>
    <firstName>Ons</firstName>
    <lastName>Chebbi</lastName>
    <address>
      <Country>Tunisia</Country>
      <city>Tunis</city>
      <zipCode>2087</zipCode>
    </address>
    <email>chebbions7@gmail.com</email>
    <phone>51746056</phone>
  </personalInformation>
  
  <education>
    <degree>
      <title>Baccalauréat en sciences expérimentales</title>
      <school>Lycée el hrairia 2</school>
      <year>2019</year>
    </degree>
    <degree>
      <title>La licence fondamentale en sciences informatiques</title>
      <school>Faculté des sciences, Tunis</school>
      <year>2019-2022</year>
    </degree>
    <degree>
      <title>Cycle d'ingénieur</title>
      <school>Tek-up</school>
      <year>2022-2025</year>
    </degree>
  </education>

  <projects>
    <project>
      <title>Projet fin d'année</title>
      <description>conception et développement d'une application web de gestion de formation</description>
      <year>2021</year>
    </project>
    <project>
      <title>Projet de fin d'étude</title>
      <description>Conception et développements d'une plateforme de gestion des matériels informatiques:Angular, Node]S,MySQL</description>
      <year>2022</year>
    </project>
    <project>
      <title>Projet Développement web</title>
      <description>site web de vente en ligne :HTML,CSS, JS, PHP</description>
      <year>2023</year>
    </project>
  </projects>

  <skills>
    <programmingLanguages>
      <language>Java</language>
      <language>Python</language>
      <language>C</language>
    </programmingLanguages>
    <frameworks>
      <framework>Angular</framework>
      <framework>Spring Boot</framework>
    </frameworks>
    <Design>
      <logiciel>AdobeXD</logiciel>
      <logiciel>Adobe Photoshop</logiciel>
    </Design>
    <languages>
      <language>English</language>
      <language>French</language>
    </languages>
  </skills>
</cv>
